apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        command: ["nginx-debug"]
        args: ["-g", "daemon off;"]
        volumeMounts:
        - mountPath: /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /data/www
          readOnly: true
          name: pod-checker
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: pod-checker
        configMap:
          name: pod-checker
          items:
            - key: pod_checker.sh
              path: pod_checker.sh
      - name: log
        emptyDir: {}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    error_log /var/log/nginx/error.log warn;

    events {
    }

    http {
      log_format  main 'remote_addr:$remote_addr\t'
                       'time_local:$time_local\t'
                       'method:$request_method\t'
                       'uri:$request_uri\t'
                       'host:$host\t'
                       'status:$status\t'
                       'bytes_sent:$body_bytes_sent\t'
                       'referer:$http_referer\t'
                       'useragent:$http_user_agent\t'
                       'request_time:$request_time';

      access_log    /var/log/nginx/access.log main;

      server {

        location / {
          root /data/www;
          index pod_checker.sh;
        } 

      }
    }

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-checker
data:
  pod_checker.sh: |
    #./podChecker.sh mountPath

    chroot $1
    if [ $? -ne 0 ]
    then
        # Return result that this pot can't chroot.
        # In other words, can't get the shell.
    fi

    #Return result that this pot can get the shell.

    # chrootは、root権限でしか実行できない
    # すなわち、chrootで奪ったシェルはroot権限になる

---

apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80